### ISSUE TITLE
A small query regarding baselines

### ISSUE THREAD

**Issue by JosephKJ** [ShipengWang/Adam-NSCL#3]
Hi @ShipengWang,

Thank you for your amazing work. This is indeed great that you have shared the code too. 

I had two queries, and it would be very kind of you if you could answer these:
* What is the memory size (in terms of number of images per task) for the baselines that use exemplar replay (GD-WILD, GEM, A-GEM and MEGA)? 
* Were all the baselines reimplemented? 

Thanks,
Joseph

**Comment by ShipengWang** [comment]
We reimplement all the baselines.
GEM, A-GEM and MEGA are re-runned with the released code with the same hyperparameters (including the number of images).

GD-WILD: the total number of images for replay is 200 for fair memory usage.

**Comment by JosephKJ** [comment]
Hi @ShipengWang. Thank you for your swift response. 

For GD-WILD, is it 200 images per class? Also, does this vary for CIFAR100-10, CIFAR-100-20 and MiniImageNet-25 experiments?

**Comment by ShipengWang** [comment]
200 images of previous tasks in total, but there are lots of wild images.
